global:
  scrape_interval: 120s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'monitoring'
    static_configs:
      - targets:
          - 'localhost:9090'
          - 'node-exporter:9100'
          - 'cadvisor:8080'
